### ISSUE TITLE
Capture output until

### ISSUE THREAD

**Issue by eerimoq** [vberlier/unicorn#2]
I want to test a shell that runs in a separate thread. Today I do it like this:

``` c
CAPTURE_OUTPUT(output) {
  // Start the shell.
  // Write to shell stdin.
  usleep(50000);
}

ASSERT_SUBSTRING(output, "OK!\n");
```

The sleep is needed to give  the shell thread some time to execute before the output is checked. It's not very pretty as the test may fail if the CPU is busy with other tasks.

I was thinking about something like this instead:

``` c
CAPTURE_OUTPUT_UNTIL("OK\n") {
  // Start the shell.
  // Write to shell stdin.
}
```

Would it be possible to add something similar to this?

**Comment by vberlier** [comment]
Hmm I guess it would be possible but then you would still need some sort of timeout. Otherwise if the thread never outputs the required substring the test would hang indefinitely. The best solution would be to join the thread before exiting the `CAPTURE_OUTPUT` block.

**Comment by eerimoq** [comment]
At the moment the thread runs indefinitely, so I was curious if I could test it unmodified. Adding logic to end it when the input is closed and use join is possible of course.

A timeout would certainly be needed. =)

**Comment by vberlier** [comment]
I'm thinking about adding something like this:

```c
ASSERT_OUTPUT("OK!") {
    // ...
}
```

This would combine `CAPTURE_OUTPUT` and `ASSERT_SUBSTRING`. This version would be synchronous but specifying a timeout as a second argument would make it wait up to the desired amount of time before failing.

```c
ASSERT_OUTPUT("OK!", 50000) {
    // ...
}
```

The issue is that the test could still fail depending on what the CPU is doing so I'm not sure if it's an actual improvement. The difference here is that the test would succeed as soon as the specified substring gets captured.

**Comment by eerimoq** [comment]
I agree, timeouts are generally not recommended as they are not reliable. I think I'll make my thread end gracefully, and I'll use the sleep for now.

Good idea to check the substring automatically. Though, sometimes, the user want to check for an exact match.

**Comment by vberlier** [comment]
Yeah I don't see a way of making things significantly better. And having access to the output as a variable is more flexible anyway. I'll think about it and maybe reopen this if I come up with a better solution :/
